### ISSUE TITLE
androidx86和chroot后的ubuntu通信成功，但是不能阻塞

### ISSUE THREAD

**Issue by ELWIN-MAO** [openthos/oto_lkp#2]
问题：
chroot后的ubuntu，通过socket向androidx86发送命令，androidx86收到命令后执行对应的命令，并返回结果给chroot的ubuntu.

但是如果一个命令，androidx86执行需要5分钟，但是ubuntu发送命令却只需要几毫秒，ubuntu发送完命令后，不会阻塞5分钟，直到androidx86执行完命令，后才会继续执行下面的命令，而是发送完命令后，直接就执行下面的命令了。导致ubuntu和androidx86同步失败。

可能的解决方法：
在androidx86上面安装dropbear ssh，ubuntu通过ssh下达命令给androidx86，达到逐条命令阻塞顺序执行的目的。实现同步。

**Comment by xyongcn** [comment]
@薛海龙 请结合毛英明和韩辉的结果，给出一个测试用例。希望能在测试时，同时控制chroot中的monitor执行和android-x86下测试用例的执行，并收集测试结果和monitor的输入。

**Comment by ELWIN-MAO** [comment]
问题已经解决：
尝试过程：
1. chroot ubuntu adb 连接 androidx86失败。【有可能adb 端口转发可以解决这个问题，但是本来一台机器2个进程间通信的问题，变成了2台机器3个进程见通信的问题，导致不稳定。】

2 未完待续
